import { describe, expect, test } from "bun:test";
import { createPasses, PassError, type PassSettlement, type PassStore } from "../src";
const records = new Map<string, PassSettlement>(); const nullifiers = new Set<string>(); const store: PassStore = { async getByRequest(id) { return records.get(id); }, async consume(value) { if (nullifiers.has(value.nullifier)) throw new Error("spent"); nullifiers.add(value.nullifier); records.set(value.requestId, structuredClone(value)); return value; } };
function passes() { records.clear(); nullifiers.clear(); return createPasses({ policy: { assetId: "USDG", denominations: [{ id: "unit-10", value: "10000000", uses: ["gas", "ai"] }] }, issuer: { async issueBlind() { return { blindSignature: "blind-signature" }; }, async verify(token) { return token === "valid-token"; } }, store, balances: { async redeem() {} }, now: () => Date.parse("2030-01-01T12:00:00.000Z") }); }
describe("Passes", () => {
 test("issues blindly and spends a fixed-denomination pass", async () => { const tool = passes(); expect((await tool.issue({ requestId: "issue-1", balanceReference: "shielded-balance", denominationId: "unit-10", blindedMessage: "blinded" })).blindSignature).toBe("blind-signature"); expect(await tool.spend({ requestId: "spend-1", denominationId: "unit-10", nullifier: "nullifier-1", unblindedToken: "valid-token", use: "gas", recipientReference: "relay-1" })).toMatchObject({ kind: "spent", value: "10000000" }); });
 test("blocks double spends and disallowed scopes", async () => { const tool = passes(); await tool.spend({ requestId: "spend-1", denominationId: "unit-10", nullifier: "same", unblindedToken: "valid-token", use: "ai", recipientReference: "ai-1" }); await expect(tool.spend({ requestId: "spend-2", denominationId: "unit-10", nullifier: "same", unblindedToken: "valid-token", use: "ai", recipientReference: "ai-1" })).rejects.toThrow("nullifier"); await expect(tool.spend({ requestId: "spend-3", denominationId: "unit-10", nullifier: "new", unblindedToken: "valid-token", use: "relay", recipientReference: "r" })).rejects.toThrow("not approved"); });
 test("redeems to the supplied shielded-balance adapter only after verification", async () => { const tool = passes(); expect((await tool.redeem({ requestId: "redeem-1", denominationId: "unit-10", nullifier: "redemption", unblindedToken: "valid-token", balanceReference: "shielded-balance" })).kind).toBe("redeemed"); await expect(tool.redeem({ requestId: "bad", denominationId: "unit-10", nullifier: "bad", unblindedToken: "bad-token", balanceReference: "shielded-balance" })).rejects.toThrow(PassError); });
});
