export type Asset='USDG'|'NVDA';
export type Draft={id:string;kind:string;asset:Asset;amount:string;fee:string;net:string;createdAt:string;details:Record<string,string>;status:'Prepared'};
export function parseUnits(value:string):bigint {if(!/^(?:0|[1-9]\d*)(?:\.\d{1,18})?$/.test(value))throw new Error('Enter a valid amount with up to 18 decimal places.');const [a='',b='']=value.split('.');const units=BigInt(a)*10n**18n+BigInt(b.padEnd(18,'0'));if(units<=0n||units>=2n**128n)throw new Error('Enter an amount greater than zero and within the supported range.');return units;}
export function formatUnits(units:bigint):string {const whole=units/10n**18n;const frac=(units%10n**18n).toString().padStart(18,'0').replace(/0+$/,'');return whole.toString()+(frac?'.'+frac:'');}
export function quote(amount:string,feeBps=20){const units=parseUnits(amount);const fee=units*BigInt(feeBps)/10000n;return{amount:formatUnits(units),fee:formatUnits(fee),net:formatUnits(units-fee)};}
export function isHex(value:string,bytes?:number){return /^0x[0-9a-f]+$/i.test(value)&&value.length%2===0&&(!bytes||value.length===bytes*2+2);}
export function validDraft(value:unknown):value is Draft{if(!value||typeof value!=='object')return false;const d=value as Draft;return typeof d.id==='string'&&typeof d.kind==='string'&&['USDG','NVDA'].includes(d.asset)&&typeof d.amount==='string'&&typeof d.fee==='string'&&typeof d.net==='string'&&typeof d.createdAt==='string'&&d.status==='Prepared'&&!!d.details&&typeof d.details==='object'&&Object.values(d.details).every(x=>typeof x==='string');}
export function readDrafts():Draft[]{try{const raw=JSON.parse(localStorage.getItem('curtain-plans-v1')||'[]');return Array.isArray(raw)?raw.filter(validDraft).slice(0,100):[]}catch{return[]}}
export function downloadFile(name:string,data:unknown){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
