export type PassUse = "gas" | "ai" | "agent-payment" | "relay";
export interface PassDenomination { id: string; value: string; uses: PassUse[]; }
export interface PassPolicy { assetId: string; denominations: PassDenomination[]; }
/** Opaque blind request; caller creates its own blinding material and never gives it to this toolkit. */
export interface PassIssuanceRequest { requestId: string; balanceReference: string; denominationId: string; blindedMessage: string; }
export interface IssuedPass { requestId: string; denominationId: string; blindSignature: string; issuedAt: string; }
export interface PassSpendRequest { requestId: string; denominationId: string; nullifier: string; unblindedToken: string; use: PassUse; recipientReference: string; }
export interface PassRedemptionRequest { requestId: string; denominationId: string; nullifier: string; unblindedToken: string; balanceReference: string; }
export interface PassSettlement { requestId: string; denominationId: string; nullifier: string; kind: "spent" | "redeemed"; value: string; settledAt: string; }
/** Integrator owns blind-signature cryptography, issuance policy, and key rotation. */
export interface PassIssuer { issueBlind(request: PassIssuanceRequest, denomination: PassDenomination): Promise<{ blindSignature: string }>; verify(token: string, denomination: PassDenomination, nullifier: string): Promise<boolean>; }
/** Must atomically enforce globally unique nullifiers and idempotent request IDs. */
export interface PassStore { getByRequest(requestId: string): Promise<PassSettlement | undefined>; consume(settlement: PassSettlement): Promise<PassSettlement>; }
/** Integrator owns shielded-balance accounting and any chain/database reconciliation. */
export interface PassBalanceAdapter { redeem(input: { balanceReference: string; assetId: string; value: string; requestId: string }): Promise<void>; }
export interface PassOptions { policy: PassPolicy; issuer: PassIssuer; store: PassStore; balances: PassBalanceAdapter; now?: () => number; }
export class PassError extends Error { constructor(message: string, public readonly code: "INVALID_POLICY" | "INVALID_REQUEST" | "INVALID_TOKEN" | "DOUBLE_SPEND" | "INVALID_SCOPE") { super(message); this.name = "PassError"; } }
/** In-process pass policy. It is not a custodian, blind-signature issuer, gas sponsor, relay, or payment processor. */
export function createPasses(options: PassOptions) {
  const now = options.now ?? (() => Date.now()); validatePolicy(options.policy); const denominations = new Map(options.policy.denominations.map((item) => [item.id, structuredClone(item)]));
  async function issue(request: PassIssuanceRequest): Promise<IssuedPass> { validateIssuance(request); const denomination = denominationFor(request.denominationId); const issued = await options.issuer.issueBlind(structuredClone(request), denomination); if (!issued || !opaque(issued.blindSignature)) throw new PassError("Issuer returned an invalid blind signature", "INVALID_TOKEN"); return { requestId: request.requestId, denominationId: denomination.id, blindSignature: issued.blindSignature, issuedAt: new Date(now()).toISOString() }; }
  async function spend(request: PassSpendRequest): Promise<PassSettlement> { validateSpend(request); const prior = await options.store.getByRequest(request.requestId); if (prior) return structuredClone(prior); const denomination = denominationFor(request.denominationId); if (!denomination.uses.includes(request.use)) throw new PassError("Pass denomination is not approved for this use", "INVALID_SCOPE"); if (!(await options.issuer.verify(request.unblindedToken, denomination, request.nullifier))) throw new PassError("Pass token verification failed", "INVALID_TOKEN"); return consume({ requestId: request.requestId, denominationId: denomination.id, nullifier: request.nullifier, kind: "spent", value: denomination.value, settledAt: new Date(now()).toISOString() }); }
  async function redeem(request: PassRedemptionRequest): Promise<PassSettlement> { validateRedemption(request); const prior = await options.store.getByRequest(request.requestId); if (prior) return structuredClone(prior); const denomination = denominationFor(request.denominationId); if (!(await options.issuer.verify(request.unblindedToken, denomination, request.nullifier))) throw new PassError("Pass token verification failed", "INVALID_TOKEN"); await options.balances.redeem({ balanceReference: request.balanceReference, assetId: options.policy.assetId, value: denomination.value, requestId: request.requestId }); return consume({ requestId: request.requestId, denominationId: denomination.id, nullifier: request.nullifier, kind: "redeemed", value: denomination.value, settledAt: new Date(now()).toISOString() }); }
  async function consume(settlement: PassSettlement): Promise<PassSettlement> { try { return structuredClone(await options.store.consume(settlement)); } catch { throw new PassError("Pass nullifier has already been consumed", "DOUBLE_SPEND"); } }
  function denominationFor(id: string): PassDenomination { const item = denominations.get(id); if (!item) throw new PassError("Unknown pass denomination", "INVALID_REQUEST"); return item; }
  return { issue, spend, redeem };
}
function validatePolicy(policy: PassPolicy): void { if (!policy || !id(policy.assetId) || !Array.isArray(policy.denominations) || policy.denominations.length === 0 || policy.denominations.length > 32) throw new PassError("Pass policy is invalid", "INVALID_POLICY"); const seen = new Set<string>(); for (const item of policy.denominations) { if (!item || !id(item.id) || seen.has(item.id) || !uint(item.value) || !Array.isArray(item.uses) || item.uses.length === 0 || item.uses.some((use) => !["gas","ai","agent-payment","relay"].includes(use))) throw new PassError("Pass denomination is invalid", "INVALID_POLICY"); seen.add(item.id); } }
function validateIssuance(value: PassIssuanceRequest): void { if (!value || !id(value.requestId) || !reference(value.balanceReference) || !id(value.denominationId) || !opaque(value.blindedMessage)) throw new PassError("Pass issuance request is invalid", "INVALID_REQUEST"); }
function validateSpend(value: PassSpendRequest): void { if (!value || !id(value.requestId) || !id(value.denominationId) || !opaque(value.nullifier) || !opaque(value.unblindedToken) || !["gas","ai","agent-payment","relay"].includes(value.use) || !reference(value.recipientReference)) throw new PassError("Pass spend request is invalid", "INVALID_REQUEST"); }
function validateRedemption(value: PassRedemptionRequest): void { if (!value || !id(value.requestId) || !id(value.denominationId) || !opaque(value.nullifier) || !opaque(value.unblindedToken) || !reference(value.balanceReference)) throw new PassError("Pass redemption request is invalid", "INVALID_REQUEST"); }
function id(value: string): boolean { return typeof value === "string" && /^[A-Za-z0-9_.:-]{1,128}$/.test(value); } function reference(value: string): boolean { return typeof value === "string" && /^[A-Za-z0-9_.:/-]{1,256}$/.test(value); } function opaque(value: string): boolean { return typeof value === "string" && value.length > 0 && value.length <= 4096; } function uint(value: string): boolean { return typeof value === "string" && /^[1-9]\d{0,77}$/.test(value) && BigInt(value) < 2n ** 256n; }
