import { describe, expect, test } from "bun:test";
import { createHonestLaunch, HonestLaunchError, type HonestLaunchStore, type LaunchAllocation, type LaunchAggregate } from "../src";
let allocations: LaunchAllocation[] = []; const byRequest = new Map<string, LaunchAllocation>();
const store: HonestLaunchStore = {
  async getByRequest(id) { return byRequest.get(id); },
  async reserve({ allocation, totalSupplyCap, launchWindowCap }) { const prior = byRequest.get(allocation.requestId); if (prior) return prior; const all = allocations.reduce((sum, item) => sum + BigInt(item.amount), 0n) + BigInt(allocation.amount); const window = allocations.filter((item) => item.allocatedAt >= "2030-01-01T12:00:00.000Z" && item.allocatedAt < "2030-01-01T13:00:00.000Z").reduce((sum, item) => sum + BigInt(item.amount), 0n) + BigInt(allocation.amount); if (all > BigInt(totalSupplyCap) || (launchWindowCap && window > BigInt(launchWindowCap))) throw new HonestLaunchError("cap", "CAP_EXCEEDED"); allocations.push(structuredClone(allocation)); byRequest.set(allocation.requestId, structuredClone(allocation)); return allocation; },
  async aggregate() { const amount = allocations.reduce((sum, item) => sum + BigInt(item.amount), 0n).toString(); return { tokenId: "launch-token", allocatedAmount: amount, allocations: allocations.length, launchWindowAllocatedAmount: amount } satisfies LaunchAggregate; },
};
const request = { requestId: "allocation-1", tokenId: "launch-token", participantReference: "participant-1", amount: "40", deployerReference: "deployer-1", fundingReferences: ["funding-1"] };
function launch(approved = true) { allocations = []; byRequest.clear(); return createHonestLaunch({ policy: { tokenId: "launch-token", launchStart: "2030-01-01T12:00:00.000Z", launchEnd: "2030-01-01T13:00:00.000Z", totalSupplyCap: "100", launchWindowCap: "50" }, screening: { async screenDeployer(reference) { return { approved, reference }; }, async screenFunding(reference) { return { approved, reference }; } }, store, signer: { async sign() { return "fixture-signature"; } }, now: () => Date.parse("2030-01-01T12:30:00.000Z") }); }
describe("Honest Launch", () => {
  test("screens allocation, enforces tighter launch cap, and publishes aggregate-only certificate", async () => { const tool = launch(); expect((await tool.allocate(request)).status).toBe("allocated"); await expect(tool.allocate({ ...request, requestId: "allocation-2", amount: "20" })).rejects.toThrow("cap"); const cert = await tool.issueCertificate(); expect(cert).toMatchObject({ signature: "fixture-signature", certificate: { aggregate: { allocatedAmount: "40", allocations: 1 } } }); expect(JSON.stringify(cert)).not.toContain("participant-1"); });
  test("rejects failed deployer or funder screening", async () => { await expect(launch(false).allocate(request)).rejects.toThrow("screening"); });
  test("rejects invalid cap policy", () => { expect(() => createHonestLaunch({ policy: { tokenId: "x", launchStart: "2030-01-01T12:00:00.000Z", launchEnd: "2030-01-01T13:00:00.000Z", totalSupplyCap: "10", launchWindowCap: "11" }, screening: {} as never, store, signer: {} as never, now: () => Date.parse("2030-01-01T12:00:00.000Z") })).toThrow(HonestLaunchError); });
});
